apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: gitlab
  labels:
    calponia.com/component: registry
    calponia.com/part-of: calponia
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS5naXRsYWIuY29tIjogewoJCQkiYXV0aCI6ICJaR2wyY21GdGIyUTZha2d0Tkd0T1VYa3pZMUpVZVV0eldDMXRaa1k9IgoJCX0KCX0sCgkiSHR0cEhlYWRlcnMiOiB7CgkJIlVzZXItQWdlbnQiOiAiRG9ja2VyLUNsaWVudC8xOC4wOS41LWNlIChsaW51eCkiCgl9Cn0=
